spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: football-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/football/**
          filters:
            - StripPrefix=2
        - id: comment-service
          uri: http://localhost:8081
          predicates:
            - Path=/comment/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: gamble-service
          uri: http://localhost:8084
          predicates:
            - Path=/gamble/**
          filters:
            - StripPrefix=1