spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: football-service
          uri: lb://football
          predicates:
            - Path=/football/**
          filters:
            - StripPrefix=2
        - id: comment-service
          uri: lb://comment
          predicates:
            - Path=/comment/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: gamble-service
          uri: lb://gamble
          predicates:
            - Path=/gamble/**
          filters:
            - StripPrefix=1