spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: football-service
          uri: lb://football
          predicates:
            - Path=/football/**
          filters:
            - StripPrefix=1
        - id: comment-service
          uri: lb://comment
          predicates:
            - Path=/comment/**
          filters:
            - StripPrefix=1
    loadbalancer:
      ribbon:
        enabled: false