spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: football-service
          uri: lb://football
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
    loadbalancer:
      ribbon:
        enabled: false